# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcXbarStar <- function(A, n_A, n_B, n_iter, xbar0_replace) {
    .Call('gleeR_calcXbarStar', PACKAGE = 'gleeR', A, n_A, n_B, n_iter, xbar0_replace)
}

calcPvals <- function(x, f) {
    .Call('gleeR_calcPvals', PACKAGE = 'gleeR', x, f)
}

